

sber.chat_url = https://gigachat.devices.sberbank.ru/api/v1/chat/completions
sber.token_url = https://ngw.devices.sberbank.ru:9443/api/v2/oauth
sber.rq_uid = f464c28a-d642-487e-a489-0cc62a2acc52
sber.model = GigaChat
sber.authorization_key = ZTBjNGJkMTYtMjgzZS00MDdkLWI1MmMtZDRiZGEzZDY0OWNhOjRhYmEyNTEyLWVkNzYtNGE3My05YWJhLTFkMjdjZjI5YWFlMg==

server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Napomica
spring.datasource.username=postgres
spring.datasource.password=28762876