CREATE TABLE IF NOT EXISTS Messages
(
    chat_id   INTEGER,
    name      VARCHAR
);

CREATE TABLE IF NOT EXISTS MessageTexts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     INTEGER,
    text        VARCHAR(500),
    dateTime    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BotMessageTexts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     INTEGER,
    text        VARCHAR(500),
    dateTime    VARCHAR(255)
);